console.log("Samparen Boiz");
//writing variables and strings together;
var FirstName = "Oberoi";

var Likes = "SkyDiving"



//console.log("My Name Is "   + FirstName + " And i like " + Likes)

//best way writing variables and strings together;
console.log(`My Name is ${FirstName} And i Like ${Likes}`)

//operators
var Age = 97;
var year = 2021;
var DOB= year - Age;
console.log(DOB)

//ASSS OPE
// = += -= /= %=

var FirstValue = 26;
var SecondValue = 10;

var LatestValue = FirstValue += SecondValue;

console.log(LatestValue)
console.log(FirstValue===SecondValue)

//binary operator

//unar operators
//logiacal operators && || !-

var Mnu = 498;
var Nmu = 589;
var Lst = 478;

console.log(Mnu<Nmu || Mnu<Lst)
var Name = "False"
console.log(Name);

var Aki = 45;
var Bad = Aki++;

console.log(Aki,Bad)

var FirstChild= "Mary";
var SecondChild = "Asom";
var FirstChildAge = 21;
 var SecondChildAge = 23;

if(FirstChildAge>SecondChildAge){
    console.log(`My Name Is ${FirstChild} and I am Aged ${FirstChildAge}`)
}
 else{
    console.log(`Sorry ${FirstChild} You're Not Old As Me 😅😂.............`)
}
